### ISSUE TITLE
Don't send the AMP MIME part if there's no AMP version

### ISSUE THREAD

**Issue by hteumeuleu** [cossssmin/sendtest.email#89]
Hi there! In Gmail desktop webmail, I keep seeing this warning when I test my regular HTML emails with SendTest.email. 

<img width="750" alt="Gmail showing a warning above the email: Why isn't the dynamic content rendered? There was an error displaying your dynamic email (INVALID_AMP)." src="https://user-images.githubusercontent.com/3451753/82112780-a2a32480-9750-11ea-9c44-b839fad1b174.png">

It's not a big deal, but it could be better if emails sent without any AMP emails content wouldn't include the AMP MIME part. (Thus avoiding to trigger this warning in Gmail.)

**Comment by cossssmin** [comment]
Yeah, I’ve noticed it too recently :)

Will have a look again when I get some time, but as far as I remember you couldn’t do that with the SparkPost API. But I might be wrong, or things might have changed since.

**Comment by cossssmin** [comment]
Fixed! 🙂

I've also moved the warning about whitelisting outside of the editor, so you don't need to delete it when sending an AMP4EMAIL test anymore.

**Comment by hteumeuleu** [comment]
That was fast! Thank you!
